'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BarChart3,Building2,CheckCircle2,Edit3,FileText,Home,LogOut,MapPin,PartyPopper,Save,Stamp,Upload,UserRound,Users} from 'lucide-react';
import {supabaseBrowser} from '../../../lib/supabase';

type SchoolRow={id:string;school_code:string;school_name:string;manager_name:string|null;stamp_path:string|null;manager_signature_path:string|null};
type Profile={gender:string;stage:string;merged_stages:string[];study_type:string;governorate:string;contact_mobile:string;address_text:string;latitude:string;longitude:string;total_students:number;total_classes:number;grade_students:Record<string,number>;signature_path:string|null;stamp_path:string|null;completed_step:number;completion_percent:number};
const empty:Profile={gender:'',stage:'',merged_stages:[],study_type:'',governorate:'',contact_mobile:'',address_text:'',latitude:'',longitude:'',total_students:0,total_classes:0,grade_students:{},signature_path:null,stamp_path:null,completed_step:0,completion_percent:0};
const stages=['ابتدائي','متوسط','ثانوي'];
const grades:Record<string,string[]>={
 'ابتدائي':['الأول الابتدائي','الثاني الابتدائي','الثالث الابتدائي','الرابع الابتدائي','الخامس الابتدائي','السادس الابتدائي'],
 'متوسط':['الأول المتوسط','الثاني المتوسط','الثالث المتوسط'],
 'ثانوي':['الأول الثانوي','الثاني الثانوي','الثالث الثانوي']
};
export default function SchoolProfile(){
 const sb=supabaseBrowser(); const [school,setSchool]=useState<SchoolRow|null>(null),[p,setP]=useState<Profile>(empty),[step,setStep]=useState(1),[manager,setManager]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 const [sigFile,setSigFile]=useState<File|null>(null),[stampFile,setStampFile]=useState<File|null>(null),[editMode,setEditMode]=useState(false),[sigUrl,setSigUrl]=useState(''),[stampUrl,setStampUrl]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href='/';return}const {data:su}=await sb.from('school_users').select('school_id,schools(id,school_code,school_name,manager_name,stamp_path,manager_signature_path)').eq('auth_user_id',user.id).eq('is_active',true).single();if(!su){setErr('لم يتم ربط الحساب بمدرسة.');return}const s=su.schools as unknown as SchoolRow;setSchool(s);setManager(s.manager_name||'');const {data}=await sb.from('school_profiles').select('*').eq('school_id',s.id).maybeSingle();if(data){setP({...empty,...data,latitude:data.latitude?.toString()||'',longitude:data.longitude?.toString()||''});
if(data.signature_path){const {data:u}=sb.storage.from('school-stamps').getPublicUrl(data.signature_path);setSigUrl(u.publicUrl)}
if(data.stamp_path){const {data:u}=sb.storage.from('school-stamps').getPublicUrl(data.stamp_path);setStampUrl(u.publicUrl)}
setStep(Math.min(4,Math.max(1,(data.completed_step||0)+1)))}else{setP(x=>({...x,signature_path:s.manager_signature_path,stamp_path:s.stamp_path}))}})()},[]);
 const chosenStages=p.stage==='مدمجة'?p.merged_stages:(p.stage?[p.stage]:[]);
 const gradeList=useMemo(()=>chosenStages.flatMap(s=>grades[s]||[]),[p.stage,p.merged_stages.join('|')]);
 const gradeSum=gradeList.reduce((n,g)=>n+Number(p.grade_students[g]||0),0);
 function valid(n:number){if(n===1)return !!school?.school_name&&!!manager.trim()&&!!p.gender&&!!p.stage&&!!p.study_type&&(p.stage!=='مدمجة'||p.merged_stages.length>1);if(n===2)return !!p.governorate&&/^05\d{8}$/.test(p.contact_mobile)&&!!p.latitude&&!!p.longitude;if(n===3)return p.total_students>=0&&p.total_classes>0&&gradeList.length>0&&gradeSum===Number(p.total_students);return !!(p.signature_path||sigFile)&&!!(p.stamp_path||stampFile)}
 const completed=[1,2,3,4].filter(valid).length,percent=completed*25;
 async function upload(file:File,kind:'signature'|'stamp'){if(!school)return null;const ext=file.name.split('.').pop()||'png',path=`${school.id}/profile-${kind}-${Date.now()}.${ext}`;const {error}=await sb.storage.from('school-stamps').upload(path,file,{upsert:true});if(error)throw error;return path}
 async function save(next=true){if(!school)return;if(!valid(step)){setErr(step===3?'يجب أن يساوي مجموع الطلاب في الصفوف إجمالي عدد الطلاب.':'أكمل جميع الحقول المطلوبة في هذه الخطوة.');return}setBusy(true);setErr('');setMsg('');try{let signature=p.signature_path,stamp=p.stamp_path;if(step===4){if(sigFile)signature=await upload(sigFile,'signature');if(stampFile)stamp=await upload(stampFile,'stamp');await sb.from('schools').update({manager_name:manager.trim(),manager_signature_path:signature,stamp_path:stamp}).eq('id',school.id)}else if(step===1){await sb.from('schools').update({manager_name:manager.trim()}).eq('id',school.id)}
 const nextP={...p,signature_path:signature,stamp_path:stamp};const done=[1,2,3,4].filter(n=>n===step?true:valid(n)).length;const {error}=await sb.from('school_profiles').upsert({school_id:school.id,gender:nextP.gender||null,stage:nextP.stage||null,merged_stages:nextP.merged_stages,study_type:nextP.study_type||null,governorate:nextP.governorate||null,contact_mobile:nextP.contact_mobile||null,address_text:nextP.address_text||null,latitude:nextP.latitude?Number(nextP.latitude):null,longitude:nextP.longitude?Number(nextP.longitude):null,total_students:nextP.total_students,total_classes:nextP.total_classes,grade_students:nextP.grade_students,signature_path:signature,stamp_path:stamp,completed_step:Math.max(p.completed_step,step),completion_percent:Math.min(100,done*25),updated_at:new Date().toISOString()});if(error)throw error;setP({...nextP,completed_step:Math.max(p.completed_step,step),completion_percent:Math.min(100,done*25)});setMsg(step===4?'اكتمل الملف الشخصي للمدرسة بنسبة 100%.':'تم حفظ الخطوة بنجاح.');if(step===4){if(signature){const {data:u}=sb.storage.from('school-stamps').getPublicUrl(signature);setSigUrl(u.publicUrl)}if(stamp){const {data:u}=sb.storage.from('school-stamps').getPublicUrl(stamp);setStampUrl(u.publicUrl)}setEditMode(false)}if(next&&step<4)setStep(step+1)}catch(e:any){setErr(e.message||'تعذر حفظ البيانات.')}finally{setBusy(false)}}
 function useLocation(){if(!navigator.geolocation){setErr('المتصفح لا يدعم تحديد الموقع.');return}navigator.geolocation.getCurrentPosition(pos=>setP(x=>({...x,latitude:pos.coords.latitude.toFixed(7),longitude:pos.coords.longitude.toFixed(7)})),()=>setErr('تعذر الحصول على الموقع. اسمح للمتصفح بالوصول إلى الموقع ثم حاول مرة أخرى.'))}
 const labels=['معلومات المدرسة','عنوان المدرسة','بيانات الطلاب','اعتماد التوقيع والختم'];
 if(p.completion_percent===100&&!editMode) return <div dir="rtl" className="min-h-screen bg-[#f4f8fb] text-[#123b38]">
  <aside className="hidden lg:flex fixed right-0 top-0 bottom-0 w-[230px] bg-gradient-to-b from-[#003d4d] to-[#062f40] text-white flex-col p-4">
   <div className="py-5 px-2 border-b border-white/10"><div className="font-black text-lg">وزارة التعليم</div><div className="text-xs text-cyan-100 mt-2">التعليم المستمر · نجران</div></div>
   <nav className="py-5 space-y-2 text-sm font-bold"><a href="/dashboard" className="flex gap-3 p-3 rounded-xl hover:bg-white/10"><Home size={19}/> الصفحة الرئيسية</a><a href="/dashboard#activities" className="flex gap-3 p-3 rounded-xl hover:bg-white/10"><PartyPopper size={19}/> الأنشطة والاحتفالات</a><a href="/dashboard#employees" className="flex gap-3 p-3 rounded-xl hover:bg-white/10"><Users size={19}/> بيانات الموظفين</a><a href="/dashboard#payroll" className="flex gap-3 p-3 rounded-xl hover:bg-white/10"><FileText size={19}/> مسيرات الرواتب</a><a href="/dashboard/indicators" className="flex gap-3 p-3 rounded-xl hover:bg-white/10"><BarChart3 size={19}/> مؤشرات الأداء</a><a href="/dashboard/profile" className="flex gap-3 p-3 rounded-xl bg-cyan-500/20 text-cyan-100"><UserRound size={19}/> الملف الشخصي <span className="mr-auto">100%</span></a></nav>
   <a href="/" className="mt-auto flex gap-2 justify-center border border-white/20 rounded-xl p-3"><LogOut size={18}/> تسجيل الخروج</a>
  </aside>
  <div className="lg:mr-[230px]">
   <header className="bg-white border-b px-5 lg:px-8 py-5 flex items-center justify-between"><div><h1 className="text-xl lg:text-2xl font-black">{school?.school_name}</h1><p className="text-sm text-slate-500">الملف الشخصي للمدرسة · مكتمل</p></div><button onClick={()=>{setEditMode(true);setStep(1)}} className="rounded-xl bg-emerald-700 text-white px-4 py-2.5 font-black flex gap-2"><Edit3 size={17}/> تعديل الملف</button></header>
   <main className="p-4 lg:p-7 max-w-7xl mx-auto">
    <section className="bg-white rounded-3xl border shadow-sm p-5 mb-5"><div className="flex flex-col lg:flex-row items-center gap-6"><div className="w-28 h-28 rounded-full flex items-center justify-center" style={{background:'conic-gradient(#10b981 360deg,#e5edf2 0)'}}><div className="w-20 h-20 rounded-full bg-white flex flex-col items-center justify-center"><b className="text-2xl">100%</b><span className="text-[10px] text-slate-500">مكتمل</span></div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 flex-1 w-full">{labels.map((x,i)=><div key={x} className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2"><CheckCircle2 size={22} className="text-emerald-600"/><b>{x}</b></div><div className="text-xs mt-2 text-emerald-700">مكتمل · 25%</div></div>)}</div></div></section>
    <div className="grid lg:grid-cols-2 gap-5">
     <section className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center gap-3 mb-5"><span className="w-10 h-10 bg-emerald-100 text-emerald-700 rounded-xl flex items-center justify-center"><Building2/></span><div><h2 className="font-black text-lg">معلومات المدرسة</h2><p className="text-xs text-slate-500">البيانات الأساسية المعتمدة</p></div></div><div className="grid grid-cols-2 gap-3 text-sm">{[['اسم المدرسة',school?.school_name],['مدير المدرسة',manager],['الجنس',p.gender],['المرحلة',p.stage==='مدمجة'?p.merged_stages.join(' - '):p.stage],['نوع الدراسة',p.study_type],['رمز المدرسة',school?.school_code]].map(([k,v])=><div key={k as string} className="rounded-xl bg-slate-50 border p-3"><div className="text-xs text-slate-500">{k}</div><b className="block mt-1">{v||'—'}</b></div>)}</div></section>
     <section className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center gap-3 mb-5"><span className="w-10 h-10 bg-blue-100 text-blue-700 rounded-xl flex items-center justify-center"><MapPin/></span><div><h2 className="font-black text-lg">عنوان المدرسة</h2><p className="text-xs text-slate-500">الموقع وبيانات التواصل</p></div></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 border p-3"><span className="text-xs text-slate-500">المحافظة / المركز</span><b className="block mt-1">{p.governorate}</b></div><div className="rounded-xl bg-slate-50 border p-3"><span className="text-xs text-slate-500">جوال التواصل</span><b className="block mt-1">{p.contact_mobile}</b></div><div className="col-span-2 rounded-xl bg-slate-50 border p-3"><span className="text-xs text-slate-500">العنوان</span><b className="block mt-1">{p.address_text||'—'}</b></div></div>{p.latitude&&p.longitude&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${p.latitude},${p.longitude}`} className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-blue-50 border border-blue-200 text-blue-700 p-3 font-black"><MapPin size={18}/> عرض موقع المدرسة على Google Maps</a>}</section>
     <section className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center gap-3 mb-4"><span className="w-10 h-10 bg-violet-100 text-violet-700 rounded-xl flex items-center justify-center"><Users/></span><h2 className="font-black text-lg">بيانات الطلاب</h2></div><div className="grid grid-cols-2 gap-3 mb-4"><div className="rounded-2xl bg-blue-50 p-4 text-center"><div className="text-sm text-blue-700">إجمالي الطلاب</div><b className="text-3xl">{p.total_students}</b></div><div className="rounded-2xl bg-violet-50 p-4 text-center"><div className="text-sm text-violet-700">عدد الفصول</div><b className="text-3xl">{p.total_classes}</b></div></div><div className="font-black mb-2">توزيع الطلاب حسب الصفوف</div><div className="grid grid-cols-2 gap-2">{gradeList.map(g=><div key={g} className="flex justify-between rounded-lg border bg-slate-50 px-3 py-2 text-sm"><span>{g}</span><b>{p.grade_students[g]||0}</b></div>)}</div><div className="mt-3 rounded-xl bg-orange-50 p-3 flex justify-between font-black"><span>الإجمالي</span><span>{gradeSum}</span></div></section>
     <section className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center gap-3 mb-4"><span className="w-10 h-10 bg-orange-100 text-orange-700 rounded-xl flex items-center justify-center"><Stamp/></span><h2 className="font-black text-lg">اعتماد التوقيع والختم</h2></div><div className="grid grid-cols-2 gap-4"><div className="rounded-2xl border p-4 text-center"><b>توقيع مدير المدرسة</b><div className="h-36 mt-3 rounded-xl bg-slate-50 flex items-center justify-center">{sigUrl?<img src={sigUrl} alt="التوقيع" className="max-h-28 max-w-full object-contain"/>:<span className="text-slate-400">محفوظ</span>}</div></div><div className="rounded-2xl border p-4 text-center"><b>ختم المدرسة</b><div className="h-36 mt-3 rounded-xl bg-slate-50 flex items-center justify-center">{stampUrl?<img src={stampUrl} alt="الختم" className="max-h-28 max-w-full object-contain"/>:<span className="text-slate-400">محفوظ</span>}</div></div></div><div className="mt-4 rounded-xl bg-emerald-50 border border-emerald-200 p-3 text-center text-emerald-700 font-black"><CheckCircle2 className="inline ml-2" size={18}/>تم اعتماد الملف الشخصي واكتماله بنسبة 100%</div></section>
    </div>
   </main>
  </div>
 </div>;
 return <main dir="rtl" className="min-h-screen bg-[#f4f8fb] text-[#123b38]">
  <header className="bg-white border-b px-5 lg:px-10 py-5 flex items-center justify-between"><div><h1 className="text-xl lg:text-2xl font-black">الملف الشخصي للمدرسة</h1><p className="text-sm text-slate-500">{school?.school_name||'حساب المدرسة'} · أكمل البيانات للاستفادة من خدمات البوابة</p></div><a href="/dashboard" className="rounded-xl border px-4 py-2 font-bold text-sm">العودة للرئيسية</a></header>
  <div className="max-w-6xl mx-auto p-4 lg:p-8">
   <section className="bg-white rounded-3xl border shadow-sm p-5 mb-5"><div className="flex flex-col lg:flex-row items-center gap-6"><div className="w-28 h-28 rounded-full flex items-center justify-center" style={{background:`conic-gradient(#10b981 ${percent*3.6}deg,#e5edf2 0)`}}><div className="w-20 h-20 rounded-full bg-white flex items-center justify-center font-black text-2xl">{percent}%</div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 flex-1 w-full">{labels.map((x,i)=>{const n=i+1,done=valid(n);return <button key={x} onClick={()=>setStep(n)} className={"rounded-2xl border p-4 text-right "+(step===n?'border-emerald-500 bg-emerald-50':'bg-white')}><div className="flex items-center gap-2"><span className={"w-8 h-8 rounded-full flex items-center justify-center font-black "+(done?'bg-emerald-500 text-white':'bg-slate-200 text-slate-600')}>{done?<CheckCircle2 size={18}/>:n}</span><b>{x}</b></div><div className="text-xs mt-2 text-slate-500">25% من الملف</div></button>})}</div></div></section>
   {err&&<div className="mb-4 rounded-xl bg-red-50 border border-red-200 text-red-700 p-3 font-bold text-sm">{err}</div>}{msg&&<div className="mb-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-700 p-3 font-bold text-sm">{msg}</div>}
   <section className="bg-white rounded-3xl border shadow-sm p-5 lg:p-7">
    <div className="flex items-center justify-between mb-6"><div><span className="text-xs text-slate-500">الخطوة {step} من 4</span><h2 className="text-2xl font-black mt-1">{labels[step-1]}</h2></div><div className="text-emerald-600 font-black text-xl">{step*25}%</div></div>
    {step===1&&<div className="grid md:grid-cols-2 gap-4">
      <label className="font-bold text-sm">اسم المدرسة<input disabled value={school?.school_name||''} className="mt-2 w-full rounded-xl border p-3 bg-slate-50"/></label>
      <label className="font-bold text-sm">مدير المدرسة *<input value={manager} onChange={e=>setManager(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label>
      <label className="font-bold text-sm">الجنس *<select value={p.gender} onChange={e=>setP({...p,gender:e.target.value})} className="mt-2 w-full rounded-xl border p-3"><option value="">اختر</option><option>بنين</option><option>بنات</option></select></label>
      <label className="font-bold text-sm">المرحلة *<select value={p.stage} onChange={e=>setP({...p,stage:e.target.value,merged_stages:[]})} className="mt-2 w-full rounded-xl border p-3"><option value="">اختر</option><option>ابتدائي</option><option>متوسط</option><option>ثانوي</option><option>مدمجة</option></select></label>
      <label className="font-bold text-sm">نوع الدراسة *<select value={p.study_type} onChange={e=>setP({...p,study_type:e.target.value})} className="mt-2 w-full rounded-xl border p-3"><option value="">اختر</option><option>حضوري</option><option>عن بعد</option></select></label>
      {p.stage==='مدمجة'&&<div className="md:col-span-2 rounded-xl bg-emerald-50 border p-4"><b>حدد المراحل المدمجة *</b><div className="flex gap-5 mt-3">{stages.map(s=><label key={s} className="flex gap-2"><input type="checkbox" checked={p.merged_stages.includes(s)} onChange={e=>setP({...p,merged_stages:e.target.checked?[...p.merged_stages,s]:p.merged_stages.filter(x=>x!==s)})}/>{s}</label>)}</div></div>}
    </div>}
    {step===2&&<div className="grid md:grid-cols-2 gap-4">
      <label className="font-bold text-sm">المحافظة / المركز *<select value={p.governorate} onChange={e=>setP({...p,governorate:e.target.value})} className="mt-2 w-full rounded-xl border p-3"><option value="">اختر</option>{['نجران','شرورة','بدر الجنوب','يدمة','لجفة','حبونا'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="font-bold text-sm">جوال التواصل *<input inputMode="numeric" maxLength={10} value={p.contact_mobile} onChange={e=>setP({...p,contact_mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} placeholder="05xxxxxxxx" className="mt-2 w-full rounded-xl border p-3"/></label>
      <label className="font-bold text-sm md:col-span-2">وصف عنوان المدرسة<input value={p.address_text} onChange={e=>setP({...p,address_text:e.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label>
      <div className="md:col-span-2 rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="flex gap-2 items-center"><MapPin size={18}/> إحداثيات المدرسة *</b><p className="text-xs text-slate-500 mt-1">استخدم موقع الجهاز ثم افتح Google Maps للتحقق.</p></div><button onClick={useLocation} className="rounded-xl bg-blue-600 text-white px-4 py-2 font-bold">تحديد موقعي الحالي</button></div><div className="grid md:grid-cols-2 gap-3 mt-4"><input value={p.latitude} onChange={e=>setP({...p,latitude:e.target.value})} placeholder="خط العرض" className="rounded-xl border p-3 bg-white"/><input value={p.longitude} onChange={e=>setP({...p,longitude:e.target.value})} placeholder="خط الطول" className="rounded-xl border p-3 bg-white"/></div>{p.latitude&&p.longitude&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${p.latitude},${p.longitude}`} className="inline-block mt-4 text-blue-700 font-black">فتح الموقع في Google Maps ←</a>}</div>
    </div>}
    {step===3&&<div>
      <div className="grid md:grid-cols-2 gap-4 mb-5"><label className="font-bold text-sm">إجمالي عدد الطلاب *<input type="number" min="0" value={p.total_students} onChange={e=>setP({...p,total_students:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">إجمالي عدد الفصول *<input type="number" min="1" value={p.total_classes} onChange={e=>setP({...p,total_classes:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label></div>
      <h3 className="font-black mb-3">توزيع الطلاب حسب الصفوف</h3><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{gradeList.map(g=><label key={g} className="rounded-xl border p-3 font-bold text-sm">{g}<input type="number" min="0" value={p.grade_students[g]||0} onChange={e=>setP({...p,grade_students:{...p.grade_students,[g]:Number(e.target.value)}})} className="mt-2 w-full rounded-lg border p-2"/></label>)}</div><div className={"mt-4 rounded-xl p-4 font-black "+(gradeSum===p.total_students?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700')}>مجموع الطلاب في الصفوف: {gradeSum} من {p.total_students}</div>
    </div>}
    {step===4&&<div className="grid md:grid-cols-2 gap-5">
      <div className="rounded-2xl border p-5"><div className="flex items-center gap-2 font-black mb-3"><Upload/> توقيع مسؤول المدرسة *</div>{p.signature_path&&<div className="text-xs text-emerald-700 mb-2">يوجد توقيع محفوظ ويمكن استبداله.</div>}<input type="file" accept="image/png,image/jpeg" onChange={e=>setSigFile(e.target.files?.[0]||null)} className="w-full border rounded-xl p-3"/></div>
      <div className="rounded-2xl border p-5"><div className="flex items-center gap-2 font-black mb-3"><Stamp/> ختم المدرسة *</div>{p.stamp_path&&<div className="text-xs text-emerald-700 mb-2">يوجد ختم محفوظ ويمكن استبداله.</div>}<input type="file" accept="image/png,image/jpeg" onChange={e=>setStampFile(e.target.files?.[0]||null)} className="w-full border rounded-xl p-3"/></div>
    </div>}
    <div className="flex justify-between gap-3 mt-8 pt-5 border-t"><button disabled={step===1} onClick={()=>setStep(step-1)} className="rounded-xl border px-5 py-3 font-black disabled:opacity-40 flex gap-2 items-center"><ArrowRight size={18}/> السابق</button><button disabled={busy} onClick={()=>save(true)} className="rounded-xl bg-emerald-700 text-white px-6 py-3 font-black disabled:opacity-50 flex gap-2 items-center">{busy?'جارٍ الحفظ…':step===4?'حفظ وإكمال الملف':'حفظ ومتابعة'} {step===4?<Save size={18}/>:<ArrowLeft size={18}/>}</button></div>
   </section>
  </div>
 </main>
}