const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const vm=require('node:vm');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const achievement={exports:{},Intl,Date};vm.runInNewContext(compile('lib/achievement.ts'),achievement);
const context={exports:{},Intl,Date,require:()=>achievement.exports};vm.runInNewContext(compile('lib/discipline.ts'),context);
const {validateDiscipline,disciplineSummary,startOfPeriod}=context.exports;
const valid={academic_year:'1448',semester:'الأول',attendance_date:achievement.exports.riyadhDate(),expected_count:'100',on_time_count:'93',late_count:'2',excused_absent_count:'3',unexcused_absent_count:'2',notes:''};
assert.equal(validateDiscipline(valid),'');
for(const invalid of [{expected_count:'0'},{on_time_count:'94'},{late_count:'-1'},{late_count:'1.5'},{late_count:''},{expected_count:'Infinity'},{attendance_date:'2099-01-01'},{attendance_date:'2026-02-30'},{academic_year:'1448-1449'}])assert.notEqual(validateDiscipline({...valid,...invalid}),'');
assert.equal(validateDiscipline({...valid,on_time_count:'0',late_count:'0',excused_absent_count:'100',unexcused_absent_count:'0'}),'');
const rows=[{expected_count:100,on_time_count:93,late_count:2,excused_absent_count:3,unexcused_absent_count:2,attendance_date:'2026-09-29'},{expected_count:10,on_time_count:5,late_count:0,excused_absent_count:0,unexcused_absent_count:5,attendance_date:'2026-09-30'}];
const summary=disciplineSummary(rows);
assert.equal(summary.total,110);assert.equal(summary.days,2);assert.ok(Math.abs(summary.regularity-98/110*100)<1e-10);assert.ok(Math.abs(summary.regularity+summary.late+summary.absence-100)<1e-10);
assert.equal(disciplineSummary([]).regularity,null,'Missing data is not zero attendance');
assert.equal(startOfPeriod('2026-03-01','آخر 7 أيام'),'2026-02-23');
assert.equal(startOfPeriod('2026-03-15','الشهر الحالي'),'2026-03-01');
console.log('PASS: counts, dates, zero attendance, weighted aggregation, missing data and cross-month date range.');
