'use client';
import { useEffect,useState } from 'react';
import { Save,ArrowRight,BarChart3,CalendarDays } from 'lucide-react';
import { supabaseBrowser } from '../../../../lib/supabase';
const choices=[20,40,60,90,100];
const empty={manager_login_percent:20,teachers_login_percent:20,teachers_tools_percent:20,students_login_percent:20,students_tools_percent:20,support_challenges_count:0,challenge_notes:''};
function riyadhParts(){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(new Date());
 const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';
 const date=get('year')+'-'+get('month')+'-'+get('day');
 const noon=new Date(date+'T12:00:00+03:00');
 const day=noon.getDay();
 const sunday=new Date(noon); sunday.setDate(noon.getDate()-day);
 const thursday=new Date(sunday); thursday.setDate(sunday.getDate()+4);
 const fmt=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
 return {today:date,day,weekStart:fmt(sunday),weekEnd:fmt(thursday),canSubmit:day>=0&&day<=4};
}
export default function MadrasatiIndicator(){
 const sb=supabaseBrowser(); const [school,setSchool]=useState<any>(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[submitted,setSubmitted]=useState(false);
 const week=riyadhParts();
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href='/';return}const {data:su}=await sb.from('school_users').select('school_id').eq('auth_user_id',user.id).eq('is_active',true).maybeSingle();if(!su){location.href='/dashboard';return}const {data:s}=await sb.from('schools').select('id,school_name').eq('id',su.school_id).single();setSchool(s);const {data:r}=await sb.from('school_madrasati_daily_indicators').select('*').eq('school_id',su.school_id).eq('indicator_date',week.weekStart).maybeSingle();if(r){setSubmitted(true);setForm({manager_login_percent:r.manager_login_percent,teachers_login_percent:r.teachers_login_percent,teachers_tools_percent:r.teachers_tools_percent,students_login_percent:r.students_login_percent,students_tools_percent:r.students_tools_percent,support_challenges_count:r.support_challenges_count,challenge_notes:r.challenge_notes||''})}})()},[]);
 async function save(){if(!school||!week.canSubmit)return;setSaving(true);setMessage('');const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('school_madrasati_daily_indicators').upsert({...form,school_id:school.id,indicator_date:week.weekStart,submitted_by:user?.id,updated_at:new Date().toISOString()},{onConflict:'school_id,indicator_date'});if(error)setMessage('تعذر الحفظ: '+error.message);else{setSubmitted(true);setMessage('تم حفظ مؤشر منصة مدرستي لهذا الأسبوع وإرساله إلى لوحة مدير النظام.')}setSaving(false)}
 const fields=[['manager_login_percent','نسبة الدخول على منصة مدرستي من قبل المدير'],['teachers_login_percent','نسبة الدخول على منصة مدرستي من قبل معلمي المواد'],['teachers_tools_percent','نسبة تفعيل المعلمين لأدوات المنصة'],['students_login_percent','نسبة الدخول على منصة مدرستي للطلاب'],['students_tools_percent','نسبة تفعيل الطلبة لأدوات المنصة']] as const;
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-5 md:p-10"><div className="max-w-3xl mx-auto"><a href="/dashboard/indicators" className="inline-flex items-center gap-2 text-sm font-bold mb-5"><ArrowRight size={18}/>العودة لنماذج المؤشرات</a><div className="rounded-2xl bg-white border shadow-sm p-6"><div className="flex gap-3 items-center mb-2"><div className="w-12 h-12 rounded-xl bg-emerald-50 text-emerald-700 grid place-items-center"><BarChart3/></div><div><h1 className="text-2xl font-black">مؤشر منصة مدرستي الأسبوعي</h1><p className="text-sm text-gray-500">{school?.school_name||'جارٍ تحميل المدرسة'}</p></div></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 border px-4 py-3 text-sm"><CalendarDays size={18}/><span className="font-bold">فترة الإدخال:</span><span>{week.weekStart} إلى {week.weekEnd} (الأحد–الخميس)</span></div>{!week.canSubmit&&<div className="mt-4 rounded-xl bg-amber-50 border border-amber-200 p-4 text-sm font-bold text-amber-900">انتهت فترة إدخال هذا الأسبوع. سيتجدد النموذج تلقائيًا يوم الأحد القادم.</div>}{submitted&&<div className="mt-4 rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-sm font-bold text-emerald-900">✓ تم إدخال مؤشر هذا الأسبوع. يمكنك تحديثه خلال الفترة من الأحد إلى الخميس، ولن يُنشأ سجل إضافي لنفس الأسبوع.</div>}<div className="grid md:grid-cols-2 gap-4 mt-6">{fields.map(([key,label])=><label key={key}><span className="block text-sm font-bold mb-2">{label}</span><select disabled={!week.canSubmit} value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})} className="w-full border rounded-xl px-4 py-3 bg-white disabled:bg-slate-100">{choices.map(v=><option key={v} value={v}>{v}%</option>)}</select></label>)}<label><span className="block text-sm font-bold mb-2">إجمالي عدد التحديات وبلاغات الدعم المقدمة من المدرسة</span><input disabled={!week.canSubmit} type="number" min="0" value={form.support_challenges_count} onChange={e=>setForm({...form,support_challenges_count:Math.max(0,Number(e.target.value)||0)})} className="w-full border rounded-xl px-4 py-3 disabled:bg-slate-100"/></label><label className="md:col-span-2"><span className="block text-sm font-bold mb-2">الملاحظات / تصنيف التحديات</span><textarea disabled={!week.canSubmit} rows={4} maxLength={1500} value={form.challenge_notes} onChange={e=>setForm({...form,challenge_notes:e.target.value})} placeholder="اكتب الملاحظات أو صنّف أبرز التحديات التي واجهت المدرسة خلال الأسبوع..." className="w-full border rounded-xl px-4 py-3 resize-y disabled:bg-slate-100"/></label></div>{message&&<div className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</div>}<button onClick={save} disabled={saving||!school||!week.canSubmit} className="mt-6 bg-[var(--navy)] text-white rounded-xl px-6 py-3 font-black inline-flex gap-2 items-center disabled:opacity-50"><Save size={18}/>{saving?'جارٍ الحفظ…':submitted?'تحديث مؤشر الأسبوع':'حفظ مؤشر الأسبوع'}</button></div></div></main>
}