'use client';
import { useEffect,useState } from 'react';
import { Save,ArrowRight,BarChart3 } from 'lucide-react';
import { supabaseBrowser } from '../../../../lib/supabase';
const choices=[20,40,60,90,100];
const empty={manager_login_percent:20,teachers_login_percent:20,teachers_tools_percent:20,students_login_percent:20,students_tools_percent:20,support_challenges_count:0};
export default function MadrasatiIndicator(){
 const sb=supabaseBrowser(); const [school,setSchool]=useState<any>(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href='/';return}const {data:su}=await sb.from('school_users').select('school_id').eq('auth_user_id',user.id).eq('is_active',true).maybeSingle();if(!su){location.href='/dashboard';return}const {data:s}=await sb.from('schools').select('id,school_name').eq('id',su.school_id).single();setSchool(s);const {data:r}=await sb.from('school_madrasati_daily_indicators').select('*').eq('school_id',su.school_id).eq('indicator_date',today).maybeSingle();if(r)setForm({manager_login_percent:r.manager_login_percent,teachers_login_percent:r.teachers_login_percent,teachers_tools_percent:r.teachers_tools_percent,students_login_percent:r.students_login_percent,students_tools_percent:r.students_tools_percent,support_challenges_count:r.support_challenges_count})})()},[]);
 async function save(){if(!school)return;setSaving(true);setMessage('');const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('school_madrasati_daily_indicators').upsert({...form,school_id:school.id,indicator_date:today,submitted_by:user?.id,updated_at:new Date().toISOString()},{onConflict:'school_id,indicator_date'});setMessage(error?'تعذر الحفظ: '+error.message:'تم حفظ مؤشرات منصة مدرستي لليوم وإرسالها إلى لوحة مدير النظام.');setSaving(false)}
 const fields=[['manager_login_percent','نسبة الدخول على منصة مدرستي من قبل المدير'],['teachers_login_percent','نسبة الدخول على منصة مدرستي من قبل معلمي المواد'],['teachers_tools_percent','نسبة تفعيل المعلمين لأدوات المنصة'],['students_login_percent','نسبة الدخول على منصة مدرستي للطلاب'],['students_tools_percent','نسبة تفعيل الطلبة لأدوات المنصة']] as const;
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-5 md:p-10"><div className="max-w-3xl mx-auto"><a href="/dashboard/indicators" className="inline-flex items-center gap-2 text-sm font-bold mb-5"><ArrowRight size={18}/>العودة لنماذج المؤشرات</a><div className="rounded-2xl bg-white border shadow-sm p-6"><div className="flex gap-3 items-center mb-2"><div className="w-12 h-12 rounded-xl bg-emerald-50 text-emerald-700 grid place-items-center"><BarChart3/></div><div><h1 className="text-2xl font-black">مؤشر منصة مدرستي</h1><p className="text-sm text-gray-500">{school?.school_name||'جارٍ تحميل المدرسة'} — {today}</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-6">{fields.map(([key,label])=><label key={key}><span className="block text-sm font-bold mb-2">{label}</span><select value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})} className="w-full border rounded-xl px-4 py-3 bg-white">{choices.map(v=><option key={v} value={v}>{v}%</option>)}</select></label>)}<label><span className="block text-sm font-bold mb-2">إجمالي عدد التحديات وبلاغات الدعم المقدمة من المدرسة</span><input type="number" min="0" value={form.support_challenges_count} onChange={e=>setForm({...form,support_challenges_count:Math.max(0,Number(e.target.value)||0)})} className="w-full border rounded-xl px-4 py-3"/></label></div>{message&&<div className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</div>}<button onClick={save} disabled={saving||!school} className="mt-6 bg-[var(--navy)] text-white rounded-xl px-6 py-3 font-black inline-flex gap-2 items-center disabled:opacity-50"><Save size={18}/>{saving?'جارٍ الحفظ…':'حفظ مؤشرات اليوم'}</button></div></div></main>
}